---
- name: Check if connection is possible with user ansible_user and public key
  command: ssh -o User={{ ansible_user }} -o ConnectTimeout={{ bootstrap_timeout }} -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ (ansible_host | default(inventory_hostname)) }} echo "Worked"
  register: bootstrap_connection_default
  delegate_to: localhost
  ignore_errors: true
  changed_when: false

- name: Check if connection is possible with user initial_user and public key
  command: ssh -o User={{ initial_user }} -o ConnectTimeout={{ bootstrap_timeout }} -o PreferredAuthentications=publickey -o PubkeyAuthentication=yes {{ (ansible_host | default(inventory_hostname)) }} echo "Worked"
  register: bootstrap_connection_initial_user
  delegate_to: localhost
  ignore_errors: true
  changed_when: false
  when:
    - bootstrap_connection_default is failed
    - initial_user is defined

- name: Check if connection is possible with user ansible_user and password initial_password
  command: sshpass -p {{ initial_password }} ssh -o User={{ ansible_user }} -o ConnectTimeout={{ bootstrap_timeout }} -o PreferredAuthentications=password -o PubkeyAuthentication=no {{ (ansible_host | default(inventory_hostname)) }} echo "Worked"
  register: bootstrap_connection_initial_password
  delegate_to: localhost
  ignore_errors: true
  changed_when: false
  when:
    - bootstrap_connection_default is failed
    - bootstrap_connection_initial_user is defined
    - bootstrap_connection_initial_user is failed
    - initial_password is defined

- name: Check if connection is possible with user initial_user and password initial_password
  command: sshpass -p {{ initial_password }} ssh -o User={{ initial_user }} -o ConnectTimeout={{ bootstrap_timeout }} -o PreferredAuthentications=password -o PubkeyAuthentication=no {{ (ansible_host | default(inventory_hostname)) }} echo "Worked"
  register: bootstrap_connection_initial_user_and_password
  delegate_to: localhost
  ignore_errors: true
  changed_when: false
  when:
    - bootstrap_connection_default is failed
    - bootstrap_connection_initial_user is defined
    - bootstrap_connection_initial_user is failed
    - bootstrap_connection_initial_password is defined
    - bootstrap_connection_initial_password is failed
    - initial_user is defined
    - initial_password is defined

- name: If connection required change of user, set desired_user
  delegate_to: localhost
  set_fact:
    desired_user: "{{ ansible_user }}"
  when:
    - bootstrap_connection_initial_user is defined
    - bootstrap_connection_initial_user is succeeded
    - initial_user is defined

- name: If connection required change of user and password, set desired_user
  delegate_to: localhost
  set_fact:
    desired_user: "{{ ansible_user }}"
  when:
    - bootstrap_connection_initial_user_and_password is defined
    - bootstrap_connection_initial_user_and_password is succeeded
    - initial_user is defined

- name: If connection required change of user, change ansible_user to initial_user
  delegate_to: localhost
  set_fact:
    ansible_user: "{{ initial_user }}"
  when:
    - bootstrap_connection_initial_user is defined
    - bootstrap_connection_initial_user is succeeded
    - initial_user is defined

- name: If connection required change of password, change password
  delegate_to: localhost
  set_fact:
    ansible_ssh_pass: "{{ initial_password }}"
    ansible_sudo_pass: "{{ initial_password }}"
  when:
    - bootstrap_connection_initial_password is defined
    - bootstrap_connection_initial_password is succeeded
    - initial_password is defined

- name: If connection required change of user and password, change ansible_user to initial_user, change password
  delegate_to: localhost
  set_fact:
    ansible_user: "{{ initial_user }}"
    ansible_ssh_pass: "{{ initial_password }}"
    ansible_sudo_pass: "{{ initial_password }}"
  when:
    - bootstrap_connection_initial_user_and_password is defined
    - bootstrap_connection_initial_user_and_password is succeeded
    - initial_user is defined
    - initial_password is defined
