---
- name: Check for existence of installed artefacts
  block:
    - name: Check if python interpreter exists
      raw: "{{ ansible_python_interpreter | default(bootstrap_python_installation_location) }} --version"
      register: bootstrap_python_interpreter_exists

    - name: Check if PyPy tar file exists
      raw: "stat /tmp/pypy{{ bootstrap_pypy_python_version }}-{{ bootstrap_pypy_version }}.tar.bz2"
      register: bootstrap_pypy_tar_file_exists

    - name: Check if pypy directory exists
      raw: "stat {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }}"
      register: bootstrap_pypy_dir_exists

    - name: Check if libtinfo symlink exists
      raw: "stat {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }}/lib/libtinfo.so.5"
      register: bootstrap_libtinfo_symlink_exists
      when: pypy_dir_exists

    - name: Check if pip is installed
      raw: "{{ ansible_python_interpreter | default(bootstrap_python_installation_location) }}  -m pip --version"
      register: bootstrap_pip_installed
      when: python_interpreter_exists
  ignore_errors: yes

- name: Download PyPy tar file
  raw: "wget -O /tmp/pypy{{ bootstrap_pypy_python_version }}-{{ bootstrap_pypy_version }}.tar.bz2 https://bitbucket.org/pypy/pypy/downloads/pypy{{ bootstrap_pypy_python_version }}-v{{ bootstrap_pypy_version }}-linux64.tar.bz2 "
  when: bootstrap_pypy_tar_file_exists | failed

- name: Extract PyPy
  raw: "mkdir -p {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }} && tar xf /tmp/pypy{{ bootstrap_pypy_python_version }}-{{ bootstrap_pypy_version }}.tar.bz2 -C {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }}/ --strip-components=1"
  when: bootstrap_pypy_dir_exists | failed
  become: true

- name: Symlink libncurses in /lib64 as libtinfo.so.5
  raw: "mkdir -p {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }}/lib && ln -snf $(ls /lib64/libncurses.so.* | tail -1) {{ ansible_python_interpreter | default(bootstrap_python_installation_location) | dirname }}/lib/libtinfo.so.5"
  when: bootstrap_libtinfo_symlink_exists | failed
  become: true

- name: Install python interpreter
  script: "install_python_binary.sh {{ ansible_python_interpreter | default(bootstrap_python_installation_location) }}"
  when: bootstrap_python_interpreter_exists|failed
  become: true

- name: Install pip
  raw: "{{ ansible_python_interpreter | default(bootstrap_python_installation_location) }}  -m ensurepip"
  when: bootstrap_pip_installed|failed
  # become: true
# - name: Install docker-py
#   raw: "{{ ansible_python_interpreter | default(bootstrap_python_installation_location) }}  -m pip install docker-py"
