---
- name: Install bootstrap packages manually
  block:
    - name: Install software for Alpine
      raw: 'LANG=C apk update ; apk add {{ bootstrap_packages }}'
      when:
        - bootstrap_distribution == 'alpine'
        - bootstrap_packages is defined
      register: alpineresult
      changed_when:
        - "'Installing' in alpineresult.stdout"
      until: alpineresult is succeeded
      retries: '{{ bootstrap_retries }}'

    - name: Install software for Archlinux
      raw: 'LANG=C pacman -Sy --noconfirm {{ bootstrap_packages }}'
      when:
        - bootstrap_distribution == 'arch'
        - bootstrap_packages is defined
      register: archlinuxresult
      changed_when:
        - "' installing python' in archlinuxresult.stdout"
      failed_when: no
      until: archlinuxresult is succeeded
      retries: '{{ bootstrap_retries }}'

    - name: Install software for Debian or Ubuntu
      raw: 'LANG=C apt-get update && apt-get install -y {{ bootstrap_packages }}'
      when:
        - bootstrap_distribution == 'debian' or bootstrap_distribution == 'ubuntu'
        - bootstrap_packages is defined
      register: debianresult
      changed_when:
        - "' 0 newly installed' not in debianresult.stdout"
      until: debianresult is succeeded
      retries: '{{ bootstrap_retries }}'

    - name: Install software for Gentoo
      raw: 'LANG=C {{ bootstrap_emerge_command }}'
      when:
        - bootstrap_distribution == 'gentoo'
        - bootstrap_packages is defined
      register: gentooresult
      changed_when:
        - "'changed' in gentooresult.stdout"
      until: gentooresult is succeeded
      retries: '{{ bootstrap_retries }}'

    - name: Install software for openSUSE
      raw: 'LANG=C zypper -n install {{ bootstrap_packages }}'
      when:
        - bootstrap_distribution == 'opensuse'
        - bootstrap_packages is defined
      register: opensuseresult
      changed_when:
        - "'Nothing' not in opensuseresult.stdout"
      until: opensuseresult is succeeded
      retries: '{{ bootstrap_retries }}'

    - name: Install software for Red Hat
      raw: 'LANG=C yum -y install {{ bootstrap_packages }}'
      when:
        - bootstrap_distribution == 'rhel' or bootstrap_distribution == 'centos' or bootstrap_distribution == 'fedora'
        - bootstrap_packages is defined
      register: redhatresult
      changed_when:
        - "'Nothing' not in redhatresult.stdout"
      until: redhatresult is succeeded
      retries: '{{ bootstrap_retries }}'
  become: yes
