---
- include: manage_known_hosts.yml

- include: check_login.yml

- name: Wait for the host to be available by SSH
  wait_for:
    port: "{{ ansible_port | default('22') }}"
    host: "{{ ansible_host | default(inventory_hostname) }}"
  delegate_to: localhost
  become: no
  when:
    - ansible_connection is defined
    - ansible_connection != "docker"
    - bootstrap_wait_for_host | bool

- name: Test connection to host including python, otherwise register package manager
  block:
    - name: Test connection to host including python (allowed to fail)
      wait_for_connection:
        timeout: "{{ bootstrap_timeout }}"
      register: bootstrap_connect
      changed_when: no

  rescue:
    - name: Register package manager
      include_tasks: register.yml

    - name: Install packages using registered package manager
      include_tasks: install.yml

    - name: Install python if there is no registered package manager
      include_tasks: install_no_package_manager.yml
      when: bootstrap_no_package_manager | default(false)

- name: Gather facts
  setup:
    gather_subset: all
  become: no

- name: Install bootstrap packages
  package:
    name: "{{ bootstrap_packages }}"
    state: present
  register: packageresult
  become: true
  until: packageresult is succeeded

- name: Install software to support stable modules
  package:
    name: "{{ bootstrap_stable_packages }}"
    state: present
  when:
    - bootstrap_stable_packages is defined
  register: packagestableresult
  become: true
  until: packagestableresult is succeeded
  notify:
    - Gather facts

- name: Install software to support preview modules
  package:
    name: "{{ bootstrap_preview_packages }}"
    state: present
  when:
    - bootstrap_preview | bool
    - bootstrap_preview_packages is defined
  register: packagepreviewresult
  become: true
  until: packagepreviewresult is succeeded
  notify:
    - Gather facts

- name: Flush handlers
  meta: flush_handlers
