---
- name: Ensure hosts are in known_hosts
  delegate_to: localhost
  auth_keys:
    servers: "{{ play_hosts }}"
  register: auth_keys_changed
  run_once: true
  when: hostname_for_known_hosts_lookup is undefined

- name: Notify if known_hosts was changed
  debug:
    msg: "SSH Known Hosts was changed. This should only happen if your server has a new OS installation. Make sure this is what you want!"
  when: auth_keys_changed.changed
  run_once: true

- name: Notify if known_hosts was changed
  pause:
    seconds: 30
  when: auth_keys_changed|changed
  run_once: true
