---
- name: Register distribution
  become: no
  check_mode: no
  block:
    - name: Register /etc/os-release file contents
      raw: test -f /etc/os-release && cat /etc/os-release
      register: os_release
      changed_when: no
      failed_when: no
      become: yes

    - name: Set variables for distribution
      set_fact:
        bootstrap_distribution: "{{ os_release.stdout | regex_search('^\\s*ID\\s*=\\s*\\\"?([a-z0-9\\._\\-]+)\\\"?\\s*$', multiline=True, ignorecase=False) | regex_replace('^\\s*ID\\s*=\\s*\\\"?([a-z0-9\\._\\-]+)\\\"?\\s*$', '\\1') }}"
        bootstrap_distribution_major_version: "{{ os_release.stdout | regex_search('^\\s*VERSION_ID\\s*=\\s*\\\"?([a-z0-9\\._\\-]+)\\\"?\\s*$', multiline=True, ignorecase=False) | regex_replace('^\\s*VERSION_ID\\s*=\\s*\\\"?([a-z0-9\\._\\-]+)\\\"?\\s*$', '\\1') | regex_search('^\\d+', multiline=False, ignorecase=False) }}"
      when:
        - os_release.rc == 0
